# -*- coding: utf-8 -*-
# vim: ft=yaml
---
grafana:
  dir: /opt/grafana
  version: '6.2.2'

  pkg:
    name: grafana
    binary: grafana
    use_upstream_archive: false
    use_upstream_repo: false
    repo:
      humanname: grafana
      name: grafana
      comments:
        - installed by salt
      enabled: 1
      gpgcheck: 1
    archive:
      name: /opt
      uri: https://dl.grafana.com/oss/release
      source: None
      source_hash: None
      trim_output: true  # works in 2018.3.2. onwards
      archive_suffix: tar.gz
      archive_format: tar
      enforce_toplevel: false          # needed for grafana
      options: '--strip-components=1'  # needed for grafana

  # Provided in `map.jinja` via. `grains.kernel`
  kernel: ''
  rootgroup: root
  group: grafana
  config_file: /etc/grafana/grafana.ini
  config: {}
  environ_file: /etc/default/grafana.sh
  environ: []
  service:
    name: grafana-server
    user: grafana
    group: grafana

  linux:
    # 'Alternatives system' priority: zero disables (default)
    altpriority: 0
